# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages:
- commit

default_language_version:
  python: python3.9

repos:
-   repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.9
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile","black","--filter-files"]